using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using RazorPagesBlehNmah.Models;
using System.Diagnostics;
using RazorPagesBlehNmah.Data;
using Microsoft.EntityFrameworkCore;

namespace RazorPagesBlehNmah.Models;

	public static class SeedData 
	{
    public static void Initialize(IServiceProvider serviceProvider)
    {
        using (var context = new RazorPagesGalleryContext(
            serviceProvider.GetRequiredService<
                DbContextOptions<RazorPagesGalleryContext>>()))
        {
            if (context == null || context.Collection == null || context.Painting == null || context.Photograph == null)
            {
                throw new ArgumentNullException("Null RazorPagesGalleryContext");
            }

            if (context.Collection.Any())
            {
                return;   // DB has been seeded
            }

            const string V = "https://news.artnet.com/app/news-upload/2019/04/PK-Ad-Parnassum-1932-copy.jpg";
            context.Collection.AddRange(
                new Collection { CollectionName = "Masks", CoverImage= V, Description= "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01") },
                new Collection { CollectionName = "Profiles", CoverImage = "https://www.paintingmania.com/arts/paul-klee/large/bust-child-115_19928.jpg?version=12.01.20", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2002-09-01") },
                new Collection { CollectionName = "Fashion", CoverImage = "https://static.independent.co.uk/s3fs-public/thumbnails/image/2013/10/14/13/klee.jpg?quality=75&width=640&height=614&fit=bounds&format=pjpg&crop=16%3A9%2Coffset-y0.5&auto=webp", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2003-09-01") },
                new Collection { CollectionName = "Color Theory", CoverImage = "https://static.wixstatic.com/media/f4938a_c84721ded67f4f98a48f55adfaa37143~mv2.jpg/v1/fill/w_560,h_588,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/f4938a_c84721ded67f4f98a48f55adfaa37143~mv2.jpg", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2002-09-01") },
                new Collection { CollectionName = "Faces", CoverImage = "https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/layered-1937-paul-klee.jpg", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2002-09-01") },
                new Collection { CollectionName = "Early Works", CoverImage = "https://images.e-flux-systems.com/146858_195effe8793b69a2ce98a5af97fcd0d4.jpg,1600", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2001-09-01") },
                new Collection { CollectionName = "Expressionism", CoverImage = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Vorhaben_%28Intention%29_by_Paul_Klee%2C_1938.jpg/800px-Vorhaben_%28Intention%29_by_Paul_Klee%2C_1938.jpg", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2003-09-01") },
                new Collection { CollectionName = "Animals", CoverImage = "https://arthistoryproject.com/site/assets/files/18580/paul-klee-one-who-understands-1934-trivium-art-history.webp", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01") }
            );
            context.SaveChanges();

            if (context.Painting.Any())
            {
                return;   // DB has been seeded
            }

            context.Painting.AddRange(
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" }
            );
            context.SaveChanges();

            if (context.Photograph.Any())
            {
                return;   // DB has been seeded
            }

            context.Photograph.AddRange(
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" }
            );
            context.SaveChanges();
        }
    }
}

