using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using RazorPagesBlehNmah.Models;
using System.Diagnostics;
using RazorPagesBlehNmah.Data;
using Microsoft.EntityFrameworkCore;

namespace RazorPagesBlehNmah.Models;

	public static class SeedData 
	{
    public static void Initialize(IServiceProvider serviceProvider)
    {
        using (var context = new RazorPagesGalleryContext(
            serviceProvider.GetRequiredService<
                DbContextOptions<RazorPagesGalleryContext>>()))
        {
            if (context == null || context.Collection == null || context.Painting == null || context.Photograph == null)
            {
                throw new ArgumentNullException("Null RazorPagesGalleryContext");
            }

            if (context.Collection.Any())
            {
                return;   // DB has been seeded
            }

            //const string V = "https://news.artnet.com/app/news-upload/2019/04/PK-Ad-Parnassum-1932-copy.jpg";
            context.Collection.AddRange(
                new Collection { CollectionName = "Kings", CoverImage = "https://i.imgur.com/ijeK4AL.jpg", Description = "Study of Fulani and the influence of the Fulani people on west Africa. Masks begin to be used more in my art. A fascination begins on how people use masks to tap into different egos.", Year = DateTime.Parse("2005-09-01") },
                new Collection { CollectionName = "Masks", CoverImage = "https://i.imgur.com/6xYybdH.jpg", Description = "Full on study of masks and how it's much more than hiding who people are. Masks are used to become different parts of ourselves and communicate with people who feel the same as us.", Year = DateTime.Parse("2005-09-01") },
                new Collection { CollectionName = "Faces", CoverImage = "https://i.imgur.com/XW3Xqst.jpg", Description = "Were faces the first masks? With no where to hide, we put on faces and convince ourselves we're ready for action. Come and explore some of these notions.", Year = DateTime.Parse("2005-09-01") },
                new Collection { CollectionName = "Animals", CoverImage = "https://i.imgur.com/DesbWBo.jpg", Description = "Animals are some of our first inspirations in art. We look to animals for spiritual connections and tapping into who we aspire to be.", Year = DateTime.Parse("2005-09-01") },
                new Collection { CollectionName = "Portraits", CoverImage = "https://i.imgur.com/2YVJkNM.jpg", Description = "Some of Bleh Nmah's early works. Simply testing out techniques and materials. We begin to see some instances of hiding our everyday face.", Year = DateTime.Parse("2005-09-01") },
                new Collection { CollectionName = "Love", CoverImage = "https://i.imgur.com/c9Z3OCm.jpg", Description = "So much inspiration with the word LOVE. So much motivation. Bleh Nmah created so much art because of Love and will continue to do so. Let's give it up for love.", Year = DateTime.Parse("2005-09-01") },
                new Collection { CollectionName = "Fragments", CoverImage = "https://i.imgur.com/QV0TZoh.jpg", Description = "Inspired by Piet Modrian and Paul Klee. We explore color theory and the emotion that comes with it. We see the experiments and begin to understand how color combinations can evoke feelings.", Year = DateTime.Parse("2005-09-01") },
                new Collection { CollectionName = "Hidden", CoverImage = "https://i.imgur.com/9Il1Fbi.jpg", Description = "Bleh Nmah is a shy person at heart. We see that in this collection 'Hidden.' So many tools out there to help us hide or help us stand out. Depends on how you look at it I guess.", Year = DateTime.Parse("2005-09-01") },
                new Collection { CollectionName = "Prints", CoverImage = "https://i.imgur.com/AchglF9.jpg", Description = "A bit of a slow time to experiment and try out some ideas. If you like to people watch and are open to new ideas. This is the collection for you.", Year = DateTime.Parse("2005-09-01") },
                new Collection { CollectionName = "City", CoverImage = "https://i.imgur.com/O2mvWFE.jpg", Description = "Speaks for itself. This is the city that Bleh Nmah grew up in. The city can make you feel wonderful and horrible at the same time. It's all up to how you approach it. Good luck!", Year = DateTime.Parse("2005-09-01") }
            );
            context.SaveChanges();

            if (context.Painting.Any())
            {
                return;   // DB has been seeded
            }

            context.Painting.AddRange(
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" },
                new Painting { CollectionID = 1, Title = "Eyes from Above", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Medium = "Oil Paint, Canvas", Location = "Chicago, Illinois", MediaLocation = "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FiNARiJXoSBLiVgZLRJCfkQ%2Fnormalized.jpg&width=4000&height=4000&quality=80" }
            );
            context.SaveChanges();

            if (context.Photograph.Any())
            {
                return;   // DB has been seeded
            }

            context.Photograph.AddRange(
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" },
                new Photograph { CollectionID = 1, Title = "Feet on the Ground", Description = "The good news is, though, that you can then copy and paste the same formula into each listing and tweak it to make it relevant to your artwork.", Year = DateTime.Parse("2005-09-01"), Location = "Vienna, Austria", MediaLocation = "https://media.cnn.com/api/v1/images/stellar/prod/181115180453-01-mars-best-moments-mars-globe-valles-marineris-enhanced.jpg?q=w_2500,h_1406,x_0,y_0,c_fill/w_1376" }
            );
            context.SaveChanges();
        }
    }
}

